/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ScratchpadPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/scratchpadview.ts
var import_obsidian = require("obsidian");
var VIEW_TYPE_SCRATCHPAD = "scratchpad-view";
var ScratchpadView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.ctx = null;
    this.drawing = false;
    this.lastX = 0;
    this.lastY = 0;
    this.canvasHistory = [];
    this.canvasIndex = -1;
    this.textHistory = [];
    this.textIndex = -1;
    this.isTyping = false;
    this.startDrawing = (e) => {
      e.preventDefault();
      this.drawing = true;
      this.canvas.focus();
      const { x, y } = this.getPointerPosition(e);
      this.lastX = x;
      this.lastY = y;
    };
    this.draw = (e) => {
      e.preventDefault();
      if (!this.drawing || !this.ctx)
        return;
      const { x, y } = this.getPointerPosition(e);
      this.ctx.strokeStyle = this.brushColor;
      this.ctx.lineWidth = this.brushSize;
      this.ctx.lineCap = "round";
      this.ctx.lineJoin = "round";
      this.ctx.beginPath();
      this.ctx.moveTo(this.lastX, this.lastY);
      this.ctx.lineTo(x, y);
      this.ctx.stroke();
      this.lastX = x;
      this.lastY = y;
    };
    this.stopDrawing = (e) => {
      e.preventDefault();
      if (!this.drawing)
        return;
      this.drawing = false;
      this.saveCanvasSnapshot();
    };
    this.canvas = document.createElement("canvas");
    this.plugin = plugin;
    this.brushColor = this.getBrushColorFromCSS();
    this.brushSize = this.getBrushSizeFromCSS();
    this.debouncedSaveCanvasSnapshot = (0, import_obsidian.debounce)(() => {
      this.saveCanvasSnapshotInternal();
    }, 600, true);
  }
  getViewType() {
    return VIEW_TYPE_SCRATCHPAD;
  }
  getDisplayText() {
    return "Scratchpad";
  }
  async onOpen() {
    this.contentEl.empty();
    this.contentEl.addClass("scratchpad-container");
    this.setupTextarea();
    this.setupActionButtons();
    this.setupCanvas();
    this.setupToolbar();
    this.scope = new import_obsidian.Scope(this.app.scope);
    await this.loadContentFromPlugin();
    this.resizeCanvas();
    if (this.canvasHistory.length === 0 && this.ctx) {
      this.saveCanvasSnapshot();
    }
    if (this.textHistory.length === 0) {
      this.saveTextSnapshot();
    }
    this.registerDrawingEvents();
    this.scope.register(["Mod"], "z", (evt) => this.handleUndo(evt));
    this.scope.register(["Mod", "Shift"], "z", (evt) => this.handleRedo(evt));
    this.scope.register(["Mod"], "y", (evt) => this.handleRedo(evt));
  }
  onResize() {
    super.onResize();
    this.resizeCanvas();
  }
  getBrushColorFromCSS() {
    return getComputedStyle(document.documentElement).getPropertyValue("--scratchpad-brush-color").trim() || "#FFFFFF";
  }
  getBrushSizeFromCSS() {
    const val = getComputedStyle(document.documentElement).getPropertyValue("--scratchpad-brush-size").trim();
    const size = parseInt(val, 10);
    return isNaN(size) ? 2 : size;
  }
  setupTextarea() {
    this.textarea = this.contentEl.createEl("textarea", {
      cls: "scratchpad-textarea",
      attr: { placeholder: "Quick notes here..." }
    });
    this.debouncedSaveTextSnapshot = (0, import_obsidian.debounce)(
      () => {
        if (this.isTyping)
          return;
        this.isTyping = true;
        this.saveTextSnapshot();
        this.isTyping = false;
      },
      600,
      true
    );
    this.textarea.addEventListener("input", this.debouncedSaveTextSnapshot);
  }
  setupActionButtons() {
    const buttonContainer = this.contentEl.createEl("div", {
      cls: "scratchpad-buttons-container"
    });
    const saveButton = buttonContainer.createEl("button", {
      cls: "scratchpad-save-button"
    });
    (0, import_obsidian.setIcon)(saveButton, "save");
    saveButton.addEventListener("click", async () => {
      await this.saveContentToPlugin();
      new import_obsidian.Notice("Scratchpad saved");
    });
    const clearNoteBtn = buttonContainer.createEl("button", {
      cls: "scratchpad-clear-notes"
    });
    (0, import_obsidian.setIcon)(clearNoteBtn, "eraser");
    clearNoteBtn.addEventListener("click", async () => {
      this.textarea.value = "";
      this.textHistory = [""];
      this.textIndex = 0;
      let currentCanvasData = "";
      if (this.canvas && this.ctx) {
        currentCanvasData = this.canvas.toDataURL("image/png");
      }
      await this.plugin.saveScratchpadContent("", currentCanvasData);
    });
    this.contentEl.appendChild(buttonContainer);
  }
  setupCanvas() {
    this.canvas.classList.add("scratchpad-canvas");
    this.canvas.tabIndex = 0;
    this.ctx = this.canvas.getContext("2d", { willReadFrequently: true });
    this.contentEl.appendChild(this.canvas);
  }
  setupToolbar() {
    const toolbar = this.contentEl.createEl("div", {
      cls: "scratchpad-toolbar"
    });
    const colorInput = toolbar.createEl("input", {
      type: "color",
      value: this.brushColor
    });
    colorInput.addEventListener("input", (e) => {
      this.brushColor = e.target.value;
    });
    const sizeSlider = toolbar.createEl("input", {
      type: "range",
      value: this.brushSize.toString(),
      attr: {
        min: "1",
        max: "20"
      }
    });
    sizeSlider.addEventListener("input", (e) => {
      this.brushSize = parseInt(e.target.value, 10);
    });
    const undoBtn = toolbar.createEl("button");
    (0, import_obsidian.setIcon)(undoBtn, "undo");
    undoBtn.addEventListener("click", () => this.undoCanvas());
    const redoBtn = toolbar.createEl("button");
    (0, import_obsidian.setIcon)(redoBtn, "redo");
    redoBtn.addEventListener("click", () => this.redoCanvas());
    const clearCanvasBtn = toolbar.createEl("button");
    (0, import_obsidian.setIcon)(clearCanvasBtn, "eraser");
    clearCanvasBtn.addEventListener("click", async () => {
      if (!this.ctx)
        return;
      this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
      this.canvasHistory = [];
      this.canvasIndex = -1;
      this.saveCanvasSnapshot();
      await this.plugin.saveScratchpadContent(this.textarea.value, "");
    });
    toolbar.empty();
    if (import_obsidian.Platform.isAndroidApp || import_obsidian.Platform.isIosApp)
      toolbar.append(colorInput, sizeSlider, undoBtn, redoBtn, clearCanvasBtn);
    else
      toolbar.append(colorInput, sizeSlider, clearCanvasBtn);
    this.contentEl.appendChild(toolbar);
  }
  registerDrawingEvents() {
    this.registerDomEvent(this.canvas, "mousedown", this.startDrawing);
    this.registerDomEvent(this.canvas, "mousemove", this.draw);
    this.registerDomEvent(this.canvas, "mouseup", this.stopDrawing);
    this.registerDomEvent(this.canvas, "mouseout", this.stopDrawing);
    this.registerDomEvent(this.canvas, "touchstart", this.startDrawing);
    this.registerDomEvent(this.canvas, "touchmove", this.draw);
    this.registerDomEvent(this.canvas, "touchend", this.stopDrawing);
    this.registerDomEvent(this.canvas, "touchcancel", this.stopDrawing);
  }
  getPointerPosition(e) {
    const rect = this.canvas.getBoundingClientRect();
    let clientX = 0;
    let clientY = 0;
    if (e instanceof MouseEvent) {
      clientX = e.clientX;
      clientY = e.clientY;
    } else if (e.touches.length > 0) {
      clientX = e.touches[0].clientX;
      clientY = e.touches[0].clientY;
    }
    return { x: clientX - rect.left, y: clientY - rect.top };
  }
  resizeCanvas() {
    const rect = this.canvas.getBoundingClientRect();
    if (!this.ctx || rect.width === 0 || rect.height === 0) {
      return;
    }
    let snapshot = null;
    if (this.canvasIndex >= 0 && this.canvasHistory[this.canvasIndex]) {
      snapshot = this.canvasHistory[this.canvasIndex];
    }
    this.ctx.save();
    this.ctx.setTransform(1, 0, 0, 1, 0, 0);
    this.canvas.width = rect.width * window.devicePixelRatio;
    this.canvas.height = rect.height * window.devicePixelRatio;
    this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
    if (snapshot) {
      const tempCanvas = document.createElement("canvas");
      tempCanvas.width = snapshot.width;
      tempCanvas.height = snapshot.height;
      const tempCtx = tempCanvas.getContext("2d");
      if (tempCtx) {
        tempCtx.putImageData(snapshot, 0, 0);
        this.ctx.drawImage(tempCanvas, 0, 0, this.canvas.width, this.canvas.height);
      }
    }
    this.ctx.restore();
    this.ctx.scale(window.devicePixelRatio, window.devicePixelRatio);
  }
  saveCanvasSnapshot() {
    this.debouncedSaveCanvasSnapshot();
  }
  saveCanvasSnapshotInternal() {
    if (!this.ctx)
      return;
    this.ctx.save();
    this.ctx.setTransform(1, 0, 0, 1, 0, 0);
    const snapshot = this.ctx.getImageData(0, 0, this.canvas.width, this.canvas.height);
    this.ctx.restore();
    if (this.canvasIndex < this.canvasHistory.length - 1) {
      this.canvasHistory = this.canvasHistory.slice(0, this.canvasIndex + 1);
    }
    this.canvasHistory.push(snapshot);
    this.canvasIndex = this.canvasHistory.length - 1;
    const MAX_CANVAS_HISTORY_SIZE = 20;
    if (this.canvasHistory.length > MAX_CANVAS_HISTORY_SIZE) {
      this.canvasHistory.shift();
      this.canvasIndex--;
    }
  }
  undoCanvas() {
    if (this.canvasIndex <= 0) {
      this.canvasIndex = -1;
      this.canvasHistory = [];
      this.resizeCanvas();
      return;
    }
    this.canvasIndex--;
    this.resizeCanvas();
  }
  redoCanvas() {
    if (this.canvasIndex >= this.canvasHistory.length - 1)
      return;
    this.canvasIndex++;
    this.resizeCanvas();
  }
  saveTextSnapshot() {
    const value = this.textarea.value;
    if (this.textIndex < 0 || value !== this.textHistory[this.textIndex]) {
      if (this.textIndex < this.textHistory.length - 1) {
        this.textHistory = this.textHistory.slice(0, this.textIndex + 1);
      }
      this.textHistory.push(value);
      this.textIndex = this.textHistory.length - 1;
      const MAX_TEXT_HISTORY_SIZE = 50;
      if (this.textHistory.length > MAX_TEXT_HISTORY_SIZE) {
        this.textHistory.shift();
        this.textIndex--;
      }
    }
  }
  undoText() {
    if (this.textIndex <= 0)
      return;
    this.textIndex--;
    this.textarea.value = this.textHistory[this.textIndex];
  }
  redoText() {
    if (this.textIndex >= this.textHistory.length - 1)
      return;
    this.textIndex++;
    this.textarea.value = this.textHistory[this.textIndex];
  }
  handleUndo(evt) {
    evt.preventDefault();
    const active = document.activeElement;
    if (active === this.textarea) {
      this.undoText();
    } else if (active === this.canvas) {
      this.undoCanvas();
    }
  }
  handleRedo(evt) {
    evt.preventDefault();
    const active = document.activeElement;
    if (active === this.textarea) {
      this.redoText();
    } else if (active === this.canvas) {
      this.redoCanvas();
    }
  }
  async saveContentToPlugin() {
    const textContent = this.textarea.value;
    let canvasContent = "";
    if (this.canvas && this.ctx) {
      canvasContent = this.canvas.toDataURL("image/png");
    }
    await this.plugin.saveScratchpadContent(textContent, canvasContent);
  }
  async loadContentFromPlugin() {
    const data = await this.plugin.loadScratchpadContent();
    if (data) {
      this.textarea.value = data.text;
      this.textHistory = [data.text];
      this.textIndex = 0;
      if (data.canvas && this.ctx) {
        const img = new Image();
        img.onload = () => {
          if (!this.ctx) {
            return;
          }
          const currentRect = this.canvas.getBoundingClientRect();
          const originalCanvasWidth = currentRect.width * window.devicePixelRatio;
          const originalCanvasHeight = currentRect.height * window.devicePixelRatio;
          const originalDevicePixelRatio = window.devicePixelRatio;
          this.canvas.width = img.width;
          this.canvas.height = img.height;
          this.ctx.setTransform(1, 0, 0, 1, 0, 0);
          this.ctx.drawImage(img, 0, 0);
          this.canvasHistory = [this.ctx.getImageData(0, 0, this.canvas.width, this.canvas.height)];
          this.canvasIndex = 0;
          this.canvas.width = originalCanvasWidth;
          this.canvas.height = originalCanvasHeight;
          this.ctx.scale(originalDevicePixelRatio, originalDevicePixelRatio);
          this.resizeCanvas();
        };
        img.onerror = (e) => {
          if (this.ctx) {
            this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
          }
          this.canvasHistory = [];
          this.canvasIndex = -1;
        };
        img.src = data.canvas;
      } else {
        if (this.ctx) {
          this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
        }
        this.canvasHistory = [];
        this.canvasIndex = -1;
      }
    } else {
      this.textarea.value = "";
      this.textHistory = [""];
      this.textIndex = 0;
      if (this.ctx) {
        this.ctx.clearRect(0, 0, this.canvas.width, this.canvas.height);
      }
      this.canvasHistory = [];
      this.canvasIndex = -1;
    }
  }
};

// src/main.ts
var SCRATCHPAD_FILE_NAME = "history.json";
var ScratchpadPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    this.registerView(VIEW_TYPE_SCRATCHPAD, (leaf) => new ScratchpadView(leaf, this));
    this.addRibbonIcon("notebook-pen", "Open scratchpad", () => {
      this.toggleView();
    });
    this.addCommand({
      id: "open-scratchpad-view",
      name: "Open scratchpad",
      callback: () => this.activateView()
    });
  }
  async saveScratchpadContent(text, canvasData) {
    const data = {
      text,
      canvas: canvasData
    };
    const filePath = this.manifest.dir + "/" + SCRATCHPAD_FILE_NAME;
    await this.app.vault.adapter.write(filePath, JSON.stringify(data));
  }
  async loadScratchpadContent() {
    const filePath = this.manifest.dir + "/" + SCRATCHPAD_FILE_NAME;
    if (await this.app.vault.adapter.exists(filePath)) {
      const content = await this.app.vault.adapter.read(filePath);
      try {
        return JSON.parse(content);
      } catch (e) {
        return null;
      }
    }
    return null;
  }
  async activateView() {
    var _a;
    const workspace = this.app.workspace;
    const existingLeaf = workspace.getLeavesOfType(VIEW_TYPE_SCRATCHPAD)[0];
    if (existingLeaf) {
      workspace.revealLeaf(existingLeaf);
      return;
    }
    const newLeaf = (_a = workspace.getRightLeaf(false)) != null ? _a : workspace.getLeaf(true);
    await newLeaf.setViewState({
      type: VIEW_TYPE_SCRATCHPAD,
      active: true
    });
    workspace.revealLeaf(newLeaf);
  }
  async toggleView() {
    const workspace = this.app.workspace;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_SCRATCHPAD);
    if (leaves.length === 0) {
      await this.activateView();
      return;
    }
    const leaf = leaves[0];
    const activeView = workspace.getActiveViewOfType(ScratchpadView);
    if (activeView && activeView.leaf === leaf) {
      const otherLeaf = workspace.getLeaf(false);
      if (otherLeaf && otherLeaf !== leaf) {
        workspace.setActiveLeaf(otherLeaf, { focus: true });
      } else {
        leaf.view.containerEl.blur();
      }
    } else {
      workspace.revealLeaf(leaf);
    }
  }
};


/* nosourcemap */